#'@title
#' Change node labels
#'
#'@description
#' Change the labels of selected nodes.
#'
#'@details
#' Modified a qgraph object generated by semPaths and change the labels of 
#' selected nodes.
#.
#'
#'@return
#' A qgrpah based on the original one, with nodeNa attributes of selected 
#'    nodes modified.
#' 
#'@param semPaths_plot A qgraph object generated by semPaths, or a similar qgrpah
#'                      object modified by other semptools functions.
#'@param rotate_resid_list A list of named lists. Each named list should have two 
#'                    named values: \code{node} and \code{to}. The first part,
#'                    \code{node}, is a character denoting the label to be changed.
#'                    It should be as appeared in the qgraph. The second part,
#'                    \code{to}, is the new label. Expression can be used in \code{to}.
#'
#'
#'@examples
#'mod_pa <- 
#'  'x1 ~~ x2
#'   x3 ~  x1 + x2
#'   x4 ~  x1 + x3
#'  '
#'fit_pa <- lavaan::sem(mod_pa, pa_example)
#'lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#'m <- matrix(c("x1",   NA,   NA,
#'                NA, "x3", "x4",
#'              "x2",   NA,   NA), byrow = TRUE, 3, 3)
#'p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'            style = "ram", 
#'            nCharNodes = 0, nCharEdges = 0,
#'            layout = m) 
#'
#'my_label_list <- list(list(node = "x3", to = "mediator"),
#'                      list(node = "x4", to = expression(gamma)))
#'  
#'p_pa2 <- change_node_label(p_pa, my_label_list)
#'plot(p_pa2)
#'
#' @export

change_node_label <- function(semPaths_plot, label_list = NULL) {
    if (is.null(label_list)) {
        stop("label_list not specified.")
      }
    if (is.null(semPaths_plot)) {
        stop("semPaths_plot not specified.")
      } else {
        if (!inherits(semPaths_plot, "qgraph")) {
            stop("semPaths_plot is not a qgraph object.")
          }
      }
    Nodes_names <- semPaths_plot$graphAttributes$Nodes$names
    Nodes_labels <- semPaths_plot$graphAttributes$Nodes$labels
    
    if (!is.list(Nodes_names)) {
        Nodes_names <- as.list(Nodes_names)
      }
    if (!is.list(Nodes_labels)) {
        Nodes_labels <- as.list(Nodes_labels)
      }

    # TO CHECK: Which one to work on? Nodes$names or Nodes$labels?
    Nodes_in <- sapply(label_list, function(x) x$node)
    if (!all(Nodes_in %in% Nodes_names)) {
        stop("One or more nodes in label_list not in semPaths_plot.")
      }
    Nodes_labels_old <- Nodes_labels
    for (i in label_list) {
        Nodes_labels[Nodes_labels == i$nod] <- i$to
      }
    # TO CHECK: Should Nodes$names and the names of the list be updated?
    
    semPaths_plot$graphAttributes$Nodes$labels <- Nodes_labels
    semPaths_plot
  }
