#' @title Get the Attribute Values of Selected Nodes
#'
#' @description Get the values of
#' an arbitrary attributes
#' of selected nodes.
#'
#' @details From a [qgraph::qgraph]
#' object generated by
#' [semPlot::semPaths], and get the
#' values of an attribute of selected
#' nodes.
#'
#' This function is designed to be a
#' general one that gets the values of the
#' attributes named by the user.
#'
#'
#' @return A named vector of the values.
#'
#' @inheritParams set_node_attribute
#'
#' @param nodes A character vector of
#' the names of nodes. If `NULL`, then
#' the values of all nodes will be
#' retrieved.
#'
#' @param attribute_name The name of
#' the attribute from which the values
#' will be retrieved.
#'
#' @examples
#' mod_pa <-
#'   'x1 ~~ x2
#'    x3 ~  x1 + x2
#'    x4 ~  x1 + x3
#'   '
#' fit_pa <- lavaan::sem(mod_pa, pa_example)
#' lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#' m <- matrix(c("x1",   NA,   NA,
#'                 NA, "x3", "x4",
#'               "x2",   NA,   NA), byrow = TRUE, 3, 3)
#' p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'             style = "ram",
#'             nCharNodes = 0, nCharEdges = 0,
#'             layout = m)
#'
#' get_node_attribute(
#'    p_pa,
#'    nodes = c("x1", "x3"),
#'    attribute_name = "color"
#' )
#' get_node_attribute(
#'    p_pa,
#'    attribute_name = "label.cex"
#' )
#'
#' @export

get_node_attribute <- function(
  semPaths_plot,
  nodes = NULL,
  attribute_name = NULL,
  check_nodes = TRUE
) {

  if (is.null(attribute_name)) {
    stop("attribute_name not specified.")
  }
  if (missing(semPaths_plot)) {
      stop("semPaths_plot not specified.")
  } else {
    plot_type <- qgraph_type(semPaths_plot)
    if (is.na(plot_type)) {
      stop("semPaths is neither a qgraph or a list of qgraphs.")
    }
  }

  # TODO:
  # - Should we support a list of qgraphs?
  #   For now, only the first qgraphs will be retrieved.
  if (plot_type == "qgraph_list") {
    semPaths_plot <- semPaths_plot[[1]]
  }

  Nodes_names <- node_names_list(semPaths_plot)

  if (is.null(nodes)) {
    nodes <- unname(Nodes_names$names_original)
  }

  Nodes_in <- nodes
  Nodes_in_id <- match_nodes(
    Nodes_in,
    Nodes_names,
    check_nodes = check_nodes
  )

  p <- n_nodes(semPaths_plot)
  attr_to_get <- semPaths_plot$graphAttributes$Nodes[[attribute_name]]

  # Expand if necessary
  if (isTRUE(length(attr_to_get) == 1)) {
    attr_to_get <- rep(attr_to_get, p)
  }

  out <- attr_to_get[Nodes_in_id]
  names(out) <- nodes
  out

}
