#' @title Get the Attribute Values of Selected Nodes
#'
#' @description Get the values of
#' an arbitrary attributes
#' of selected nodes.
#'
#' @details From a [qgraph::qgraph]
#' object generated by
#' [semPlot::semPaths], and get the
#' values of an attribute of selected
#' nodes.
#'
#' This function is designed to be a
#' general one that gets the values of the
#' attributes named by the user.
#'
#'
#' @return A named vector of the values.
#'
#' @param semPaths_plot A
#' [qgraph::qgraph] object generated by
#' [semPlot::semPaths], or a similar
#' qgraph object modified by other
#' [semptools] functions.
#'
#' @param nodes A character vector of
#' the names of nodes.
#'
#' @param attribute_name The name of
#' the attribute from which the values
#' will be retrieved.
#'
#' @examples
#' mod_pa <-
#'   'x1 ~~ x2
#'    x3 ~  x1 + x2
#'    x4 ~  x1 + x3
#'   '
#' fit_pa <- lavaan::sem(mod_pa, pa_example)
#' lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#' m <- matrix(c("x1",   NA,   NA,
#'                 NA, "x3", "x4",
#'               "x2",   NA,   NA), byrow = TRUE, 3, 3)
#' p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'             style = "ram",
#'             nCharNodes = 0, nCharEdges = 0,
#'             layout = m)
#'
#' get_node_attribute(p_pa, "color")
#' get_node_attribute(p_pa, "label.cex")
#'
#' @export

get_node_attribute <- function(semPaths_plot,
                               nodes = NULL,
                               attribute_name = NULL) {

  if (is.null(nodes)) {
      stop("nodes not specified.")
    }
  if (is.null(attribute_name)) {
      stop("attribute_name not specified.")
    }
  if (missing(semPaths_plot)) {
      stop("semPaths_plot not specified.")
    } else {
      if (!inherits(semPaths_plot, "qgraph")) {
          stop("semPaths_plot is not a qgraph object.")
        }
    }

  Nodes_names <- semPaths_plot$graphAttributes$Nodes$names

  # Convert to a named vector
  nodes_org <- nodes
  names(nodes) <- nodes

  # Check nodes
  if (!all(nodes %in% Nodes_names)) {
    stop("One or more nodes not in semPaths_plot.")
  }
  Nodes_id <- seq_len(length(Nodes_names))
  names(Nodes_id) <- Nodes_names

  p <- n_nodes(semPaths_plot)
  attr_old <- semPaths_plot$graphAttributes$Nodes[[attribute_name]]
  if (is.null(attr_old)) {
    stop("attribute_name not a valid attribute of the nodes in a qgraph object.")
  }

  # Expand if necessary
  if (isTRUE(length(attr_old) == 1)) {
    attr_old <- rep(attr_old, p)
  }

  out <- attr_old[Nodes_id[nodes]]
  names(out) <- nodes
  out

}
