#' @title Get the Attribute Values of Selected Edges
#'
#' @description Get the values of
#' an arbitrary
#' attribute of selected edges.
#'
#' @details From a [qgraph::qgraph()]
#' object generated by
#' [semPlot::semPaths()], get the
#' values of an attribute of selected
#' edges.
#'
#' This function is designed to be a
#' general one that gets the values of the
#' attributes named by the user.
#'
#'
#' ## Setting the value of `values`
#'
#' This argument can be set in three ways.
#'
#' For a named vector, the name of an
#' element should be the path as
#' specified by [lavaan::model.syntax]
#' or as appeared in
#' [lavaan::parameterEstimates()].
#'
#' For example, if the attributes to be
#' changed are the colors of selected
#' edges, to change the color of the
#' path regressing `y` on `x`, the name
#' should be `"y ~ x"`. To change the
#' color of the covariance between `x1`
#' and `x2`, the name should be `"x1 ~~
#' x2"`. Therefore, `c("y ~ x1" = "red",
#' "x1 ~~ x2" = "blue")` changes the
#' colors of the path from `x1` to `y`
#' and the covariance between `x1` and
#' `x2` to `"red"` and `"blue"`,
#' respectively.
#'
#' The order of the two nodes *may*
#' matter for covariances. Therefore, if
#' the attribute of a covariance is not
#' changed, try switching the order of
#' the two nodes.
#'
#' For a list of named lists, each named
#' list should have three named values:
#' `from`, `to`, and `new_value`. The
#' attribute of the edge from `from` to
#' `to` will be set to `new_value`.
#'
#' The second approach is no longer
#' recommended, though kept for backward
#' compatibility.
#'
#' The last approach is setting `values`
#' to a one-element vector with *no* *name*.
#' All edges in plot will then have the
#' selected attributes set to this value.
#'
#' @return A named vector of the values.
#'
#' @inheritParams set_node_attribute
#'
#' @param edges A character vector of
#' the edges. Each edge is denoted by
#' `lavaan` model syntax, such as `y ~ x`
#' or `x1 ~~ x2`.
#' If `NULL`, then
#' the values of all edges will be
#' retrieved.
#'
#' @param attribute_name The name of
#' the attribute from which the values
#' will be retrieved.
#'
#' @param check_direction If `FALSE`,
#' the direction of an edge is ignored.
#' For example, both `y ~ x` and `x ~ y`
#' will affect `y ~ x`, `x ~ y`, and
#' `y ~~ x`. Useful when we want to
#' identify an edge regardless of its
#' direction and whether it is directional.
#'
#' @examples
#' mod_pa <-
#'   'x1 ~~ x2
#'    x3 ~  x1 + x2
#'    x4 ~  x1 + x3
#'   '
#' fit_pa <- lavaan::sem(mod_pa, pa_example)
#' lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#' m <- matrix(c("x1",   NA,   NA,
#'                 NA, "x3", "x4",
#'               "x2",   NA,   NA), byrow = TRUE, 3, 3)
#' p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'             style = "ram",
#'             nCharNodes = 0, nCharEdges = 0,
#'             layout = m)
#'
#' get_edge_attribute(
#'    p_pa,
#'    edges = c("x2 ~~ x1", "x4 ~ x1"),
#'    attribute_name = "labels")
#'
#' get_edge_attribute(
#'    p_pa,
#'    edges = c("x2 ~~ x1", "x4 ~ x1"),
#'    attribute_name = "color")
#'
#' @export

get_edge_attribute <- function(
  semPaths_plot,
  edges = NULL,
  attribute_name = NULL,
  check_direction = TRUE
) {
  if (is.null(attribute_name)) {
    stop("attribute_name not specified.")
  }
  if (missing(semPaths_plot)) {
      stop("semPaths_plot not specified.")
  } else {
    plot_type <- qgraph_type(semPaths_plot)
    if (is.na(plot_type)) {
      stop("semPaths is neither a qgraph or a list of qgraphs.")
    }
  }

  # TODO:
  # - Should we support a list of qgraphs?
  #   For now, only the first qgraphs will be retrieved.
  if (plot_type == "qgraph_list") {
    semPaths_plot <- semPaths_plot[[1]]
  }

  Nodes_names <- semPaths_plot$graphAttributes$Nodes$names
  Nodes_id <- seq_len(length(Nodes_names))
  names(Nodes_id) <- Nodes_names
  p <- n_edges(semPaths_plot)
  attr_old <- semPaths_plot$graphAttributes$Edges[[attribute_name]]
  if (is.null(attr_old)) {
    stop("attribute_name not a valid attribute of the edges a qgraph object.")
  }

  # Expand if necessary
  if (isTRUE(length(attr_old) == 1)) {
    attr_old <- rep(attr_old, p)
  }
  attr_mode <- mode(attr_old)

  e_table <- edge_names(semPaths_plot)

  # Convert a named vector to a named list
  if (is.null(edges)) {
    edges <- e_table$name[!e_table$drop]
  }
  values_dummy <- edges
  names(values_dummy) <- edges
  values <- to_list_of_lists(
          values_dummy,
          name1 = "from",
          name2 = "to",
          name3 = "name"
        )

  # ==== Get edge index ====

  attr_index <- sapply(values, function(x) {
        edge_index(semPaths_plot, from = x$from, to = x$to)
      })
  if (!check_direction) {
    attr_index2 <- sapply(values, function(x) {
          edge_index(semPaths_plot, from = x$to, to = x$from)
        })
    attr_index[is.na(attr_index)] <-
      attr_index2[is.na(attr_index)]
  }
  # 2026-06-07: Edges not in the plot will
  #             now be skipped. No error message.

  # ==== No valid edges ====

  if (all(is.na(attr_index))) {
    out <- vector(attr_mode, length(edges))
    out[] <- NA
    names(out) <- edges
    return(out)
  }

  out <- attr_old[attr_index]
  names(out) <- edges

  out
}

