#' @title Move Nodes in a Plot
#'
#' @description Move the nodes in an
#' plot generated by [semPlot::semPaths()].
#'
#' @details Modify a [qgraph::qgraph]
#' object generated by
#' [semPlot::semPaths] and move selected
#' nodes.
#'
#' The change assumes that the layout
#' is defined with 0 as the center,
#' -1 to 1 from left to right, and
#' from bottom to top.
#'
#' @return A [qgraph::qgraph] based on
#' the original one, with the selected
#' nodes moved.
#'
#' @inheritParams set_node_attribute
#'
#' @param move_by A named list. The
#' names are the names of nodes to be
#' moved. Each element of the list can
#' be either a named numeric vector or
#' an unnamed vector of two numbers. If
#' a named vector, `x` is the horizontal
#' change in the position (e.g., .25
#' means moving to the right by .25, and
#' -.5 means moving to the left by .5),
#' and `y` is the vertical change (e.g.,
#' .5 means moving up by .5, and -.1
#' means moving down by .1). If unnamed,
#' then the vector must have two numbers,
#' the first for the horizontal move (`x`)
#' and the second for the vertical move.
#' The value is interpreted based on
#' the unit of the plot, usually from
#' -1 to 1 for `x` and `y`, with 0 being
#' the center of the plot.
#'
#' @examples
#' mod_pa <-
#'   'x1 ~~ x2
#'    x3 ~  x1 + x2
#'    x4 ~  x1 + x3
#'   '
#' fit_pa <- lavaan::sem(mod_pa, pa_example)
#' lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#' m <- matrix(c("x1",   NA,   NA,
#'                 NA, "x3", "x4",
#'               "x2",   NA,   NA), byrow = TRUE, 3, 3)
#' p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'             style = "ram",
#'             nCharNodes = 0, nCharEdges = 0,
#'             layout = m)
#'
#' p_changed <- move_node(p_pa,
#'                        list(x3 = c(x = -.25, y = -.25),
#'                             x4 = c(y = .5)))
#' plot(p_changed)
#'
#' @export

move_node <- function(
              semPaths_plot,
              move_by = NULL,
              check_nodes = TRUE) {

    if (is.null(move_by)) {
        stop("move_by not specified.")
      }
    if (missing(semPaths_plot)) {
        stop("semPaths_plot not specified.")
      }

    if (missing(semPaths_plot)) {
      stop("semPaths_plot not specified.")
    } else {
      plot_type <- qgraph_type(semPaths_plot)
      if (is.na(plot_type)) {
        stop("semPaths is neither a qgraph or a list of qgraphs.")
      }
    }

    if (plot_type == "qgraph_list") {

      # ==== For a list of qgraphs =====

      my_call <- match.call()
      my_args <- as.list(my_call)[-1]
      my_args$semPaths_plot <- NULL
      for (i in seq_along(my_args)) {
        my_args[[i]] <- eval(
                          my_args[[i]],
                          envir = parent.frame(),
                          enclos = parent.frame()
                        )
      }
      out <- lapply(
        semPaths_plot,
        function(x) {
          args <- my_args
          args$semPaths_plot <- x
          do.call(
            move_node,
            args
          )
        }
      )

    }

    if (plot_type == "qgraph") {

    # ==== For one qgraph =====

    Nodes_names <- node_names_list(semPaths_plot)

    # Check nodes
    # move_by can only be a named list
    Nodes_in <- names(move_by)
    Nodes_in_id <- match_nodes(
      Nodes_in,
      Nodes_names,
      check_nodes = check_nodes
    )
    if (all(is.na(Nodes_in_id))) {
      # No valid nodes
      return(semPaths_plot)
    } else if (any(is.na(Nodes_in_id))) {
      move_by <- move_by[!is.na(Nodes_in_id)]
    }

    # The names are Node$names
    layout_org <- qgraph_to_layoutxy(semPaths_plot)

    layout_new <- layout_org
    for (x in seq_along(Nodes_in_id)) {
      move_by_i <- move_by[[x]]
      if (is.null(names(move_by_i))) {
        new_x <- move_by_i[1]
        new_y <- move_by_i[2]
      } else {
        new_x <- move_by_i["x"]
        new_y <- move_by_i["y"]
      }
      if (!is.na(new_x)) {
        layout_new[Nodes_in_id[x], "x"] <-
          layout_new[Nodes_in_id[x], "x"] + new_x
      }
      if (!is.na(new_y)) {
        layout_new[Nodes_in_id[x], "y"] <-
          layout_new[Nodes_in_id[x], "y"] + new_y
      }
    }

    layout_final <- layout_new
    rownames(layout_final) <- colnames(layout_final) <- NULL
    semPaths_plot$layout <- layout_final

    return(semPaths_plot)

    }

    # ==== Return a list of qgraphs ====

    out <- copy_class_and_attributes(
      out,
      semPaths_plot
    )

    return(out)

  }
