#' @title Move Nodes in a Plot
#'
#' @description Move the nodes in an
#' plot generated by [semPlot::semPaths()].
#'
#' @details Modify a [qgraph::qgraph]
#' object generated by
#' [semPlot::semPaths] and move selected
#' nodes.
#'
#' (TODO: How to use it)
#'
#' @return A [qgraph::qgraph] based on
#' the original one, with the selected
#' nodes moved.
#'
#' @param semPaths_plot A
#' [qgraph::qgraph] object generated by
#' [semPlot::semPaths], or a similar
#' qgraph object modified by other
#' [semptools] functions.
#'
#' @param values A named vector or a
#' list of named list. See the Details
#' section on how to set this argument.
#'
#' @param attribute_name The name of
#' the attribute to be changed.
#'
#' @examples
#' mod_pa <-
#'   'x1 ~~ x2
#'    x3 ~  x1 + x2
#'    x4 ~  x1 + x3
#'   '
#' fit_pa <- lavaan::sem(mod_pa, pa_example)
#' lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#' m <- matrix(c("x1",   NA,   NA,
#'                 NA, "x3", "x4",
#'               "x2",   NA,   NA), byrow = TRUE, 3, 3)
#' p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'             style = "ram",
#'             nCharNodes = 0, nCharEdges = 0,
#'             layout = m)
#'
#' # TODO: Update the example
#'
#' @noRd

move_node <- function(
              semPaths_plot,
              move_by = NULL) {

    if (is.null(move_by)) {
        stop("values not specified.")
      }
    if (missing(semPaths_plot)) {
        stop("semPaths_plot not specified.")
      } else {
        if (!inherits(semPaths_plot, "qgraph")) {
            stop("semPaths_plot is not a qgraph object.")
          }
      }

    # Convert a named vector to a named list
    # This should not be needed as move_by is always a list
    # if (!is.list(move_by)) {
    #     move_by_org <- move_by
    #     values <- to_list_of_lists(move_by,
    #                                name1 = "node",
    #                                name2 = "new_value")
    #   }

    # Check nodes
    Nodes_in <- names(move_by)
    Nodes_names <- semPaths_plot$graphAttributes$Nodes$names
    if (!is.null(names(Nodes_names))) {
      Nodes_names <- names(Nodes_names)
    }
    if (!all(Nodes_in %in% Nodes_names)) {
        stop("One or more nodes not in semPaths_plot.")
      }
    Nodes_id <- seq_len(length(Nodes_names))
    names(Nodes_id) <- Nodes_names

    layout_org <- qgraph_to_layoutxy(semPaths_plot)

    layout_new <- layout_org
    for (x in names(move_by)) {
      move_by_i <- move_by[[x]]
      if (is.null(names(move_by_i))) {
        new_x <- move_by_i[1]
        new_y <- move_by_i[2]
      } else {
        new_x <- move_by_i["x"]
        new_y <- move_by_i["y"]
      }
      if (!is.na(new_x)) {
        layout_new[x, "x"] <- layout_new[x, "x"] + new_x
      }
      if (!is.na(new_y)) {
        layout_new[x, "y"] <- layout_new[x, "y"] + new_y
      }
    }

    layout_final <- layout_new
    rownames(layout_final) <- colnames(layout_final) <- NULL
    semPaths_plot$layout <- layout_final

    semPaths_plot
  }
