#' @title Set the Line Widths of Selected Edges
#'
#' @description Set the line widths of
#' selected edges.
#'
#' @details Modified a [qgraph::qgraph]
#' object generated by
#' [semPlot::semPaths] and change the
#' widths of selected edges.
#'
#' ## Setting the value of `line_width_list`
#'
#' This argument can be set in three ways.
#'
#' For a named vector, the name of an
#' element should be the path as
#' specified by [lavaan::model.syntax]
#' or as appeared in
#' [lavaan::parameterEstimates()].
#'
#' For example, to change the line width of the
#' path regressing `y` on `x`, the name
#' should be `"y ~ x"`. To change the
#' line type of the covariance between `x1`
#' and `x2`, the name should be `"x1 ~~
#' x2"`. Therefore, `c("y ~ x1" = 2,
#' "x1 ~~ x2" = 3)` changes the
#' line widths of the path from `x1` to `y`
#' and the covariance between `x1` and
#' `x2`by 2 and 3,
#' respectively.
#'
#' The order of the two nodes *may*
#' matter for covariances. Therefore, if
#' the attribute of a covariance is not
#' changed, try switching the order of
#' the two nodes.
#'
#' For a list of named lists, each named
#' list should have three named values:
#' `from`, `to`, and `new_line_width`. The
#' attribute of the edge from `from` to
#' `to` will be set to `new_line_width`.
#'
#' The second approach is no longer
#' recommended, though kept for backward
#' compatibility.
#'
#' The third approach is one single
#' *unnamed* value. This value will be
#' applied to all edges.
#'
#' @return A [qgraph::qgraph] based on
#' the original one, with widths for
#' selected edges changed.
#'
#'
#' @inheritParams set_edge_attribute
#'
#' @param line_width_list A named vector or a
#' list of named list. See the Details
#' section on how to set this argument.
#'
#' @examples
#' mod_pa <-
#'   'x1 ~~ x2
#'    x3 ~  x1 + x2
#'    x4 ~  x1 + x3
#'   '
#' fit_pa <- lavaan::sem(mod_pa, pa_example)
#' lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#' m <- matrix(c("x1",   NA,   NA,
#'                 NA, "x3", "x4",
#'               "x2",   NA,   NA), byrow = TRUE, 3, 3)
#' p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'             style = "ram",
#'             nCharNodes = 0, nCharEdges = 0,
#'             layout = m)
#'
#' my_line_width_vector <- c(
#'    "x2 ~~ x1" = 2,
#'    "x4 ~ x1" = 3
#' )
#'
#' p_pa2v <- set_edge_line_width(
#'  p_pa,
#'  my_line_width_vector)
#' plot(p_pa2v)
#'
#' my_line_width_list <- list(
#'    list(
#'      from = "x1",
#'      to = "x2",
#'      new_line_width = 2),
#'    list(
#'      from = "x1",
#'      to = "x4",
#'      new_line_width =  3)
#'  )
#'
#' p_pa2l <- set_edge_line_width(
#'    p_pa,
#'    my_line_width_list
#'  )
#' plot(p_pa2l)
#'
#' @export

set_edge_line_width <- function(
  semPaths_plot,
  line_width_list = NULL,
  how = c("ratio", "value"),
  check_direction = TRUE
) {

  how <- match.arg(how)

  if (is.null(line_width_list)) {
    stop("line_width_list not specified.")
  }
  if (missing(semPaths_plot)) {
    stop("semPaths_plot not specified.")
  }

  set_all_edges <- is.null(names(line_width_list))

  # Fix the names
  line_width_list_fixed <- to_new_value(
      line_width_list,
      original_name = "new_line_width"
    )

  if (set_all_edges) {
    line_width_list_fixed <- unname(line_width_list_fixed)
  }

  out <- set_edge_attribute(
          semPaths_plot = semPaths_plot,
          values = line_width_list_fixed,
          attribute_name = "width",
          how = how,
          check_direction = check_direction
        )

  out
}
