#' @title Set Selected Attributes of a
#' Plot
#'
#' @description Set some attributes of
#' a plot.
#'
#' @details
#' Functions that modify a [qgraph::qgraph]
#' object generated by
#' [semPlot::semPaths] and change the
#' widths of selected attributes.
#'
#' For numerical attributes, there are
#' two possible modes.
#'
#' If `how = "ratio"`, then the new value
#' is equal to the old value multiplied
#' by the user value. For example, if
#' the original margins are `c(2, 3, 4, 5)`
#' and the user value is 2, then the new
#' margins are `c(4, 6, 8, 10)`. If the
#' user values are `c(3, 1, 1, 1)`, then
#' the new margins are `c(6, 3, 4, 5)`.
#'
#' If `how = "value"`, then the new value
#' is equal to the user value. For example, if
#' the original margins are `c(2, 3, 4, 5)`
#' and the user value is 2, then the new
#' margins are `c(2, 2, 2, 2)`. If
#' the user values are `c(1, 3, 5, 7)`,
#' then the new margins are `c(1, 3, 5, 7)`.
#'
#' @inheritParams set_edge_attribute
#'
#' @param bottom,left,right,top The values
#' for the corresponding sides. Please
#' refer to 'Details' on how these values
#' are used. Their default values depend
#' on `how`: Equal to 1 if `how = "ratio"`,
#' and equal to the original values if
#' `how = "value"`.
#'
#' @examples
#' mod_pa <-
#'   'x1 ~~ x2
#'    x3 ~  x1 + x2
#'    x4 ~  x1 + x3
#'   '
#' fit_pa <- lavaan::sem(mod_pa, pa_example)
#' lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#' m <- matrix(c("x1",   NA,   NA,
#'                 NA, "x3", "x4",
#'               "x2",   NA,   NA), byrow = TRUE, 3, 3)
#' p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'             style = "ram",
#'             nCharNodes = 0, nCharEdges = 0,
#'             layout = m)
#'
#' @name set_graph_attributes
NULL

#' @details
#' The function [set_graph_margins()] is
#' for modifying the margins of a generated
#' plot. It can be useful for increasing
#' or decreasing one or more margins of
#' a plot without regenerating it.
#'
#' @examples
#'
#' # ==== set_graph_margins ====
#'
#' p2 <- set_graph_margins(p_pa, bottom = 2)
#' plot(p2)
#'
#' p3 <- set_graph_margins(p_pa, bottom = 2, how = "value")
#' plot(p3)
#'
#'
#' @rdname set_graph_attributes
#' @export
set_graph_margins <- function(
  semPaths_plot,
  bottom,
  left,
  top,
  right,
  how = c("ratio", "value")
) {

  how <- match.arg(how)

  if (missing(semPaths_plot)) {
    stop("semPaths_plot not specified.")
  }

  mar_old <- semPaths_plot$plotOptions$mar

  if (missing(bottom)) {
    bottom <- switch(
      how,
      ratio = 1,
      value = mar_old[1]
    )
  }
  if (missing(left)) {
    left <- switch(
      how,
      ratio = 1,
      value = mar_old[2]
    )
  }
  if (missing(top)) {
    top <- switch(
      how,
      ratio = 1,
      value = mar_old[3]
    )
  }
  if (missing(right)) {
    right <- switch(
      how,
      ratio = 1,
      value = mar_old[4]
    )
  }

  mar_new_value <- c(bottom, left, top, right)
  mar_new <- switch(
    how,
    ratio = mar_new_value * mar_old,
    value = mar_new_value
  )

  out <- semPaths_plot
  out$plotOptions$mar <- mar_new
  out

}


#' @details
#' The function [node_labels_equal_scale()] is
#' for setting the value `label.scale.equal`
#' of a plot. By default, `label.scale.equal`
#' may be `FALSE`, and the labels of nodes
#' may be of different font sizes.
#' Use this function, with `equal_scale`
#' set to `TRUE`, will make all node labels
#' have the same font size.
#'
#' The function [set_node_labels_equal_scale()]
#' is just a wrapper of [node_labels_equal_scale()]
#' with `equal_scale` set to `TRUE`.
#'
#' @param equal_scale Logical. Set the value
#' `label.scale.equal` of the plot. If
#' not supplied, it will not change the
#' existing value.
#'
#' @examples
#'
#' # ==== node_labels_equal_scale ====
#'
#' dat <- pa_example
#' colnames(dat)[1] <- "Mediator"
#' mod_pa2 <-
#'   'x1 ~~ x2
#'    Mediator ~  x1 + x2
#'    x4 ~  x1 + Mediator
#'   '
#' fit_pa2 <- lavaan::sem(mod_pa2, dat)
#' m2 <- matrix(c("x1",   NA,   NA,
#'                 NA, "Mediator", "x4",
#'               "x2",   NA,   NA), byrow = TRUE, 3, 3)
#' p_pa2 <- semPlot::semPaths(fit_pa2, whatLabels="est",
#'             style = "ram",
#'             nCharNodes = 0, nCharEdges = 0,
#'             sizeMan = 10,
#'             layout = m2)
#'
#' p4 <- node_labels_equal_scale(p_pa2, TRUE)
#' plot(p4)
#'
#' p5 <- set_node_labels_equal_scale(p_pa2)
#' plot(p5)
#'
#' @rdname set_graph_attributes
#' @export
node_labels_equal_scale <- function(
  semPaths_plot,
  equal_scale
) {

  if (missing(semPaths_plot)) {
    stop("semPaths_plot not specified.")
  }

  if (missing(semPaths_plot)) {
    stop("semPaths_plot not specified.")
  } else {
    plot_type <- qgraph_type(semPaths_plot)
    if (is.na(plot_type)) {
      stop("semPaths is neither a qgraph or a list of qgraphs.")
    }
  }

  if (plot_type == "qgraph_list") {

    # ==== For a list of qgraphs =====

    # Need to use this approach because
    # equal_scale may be missing

    my_call <- match.call()
    my_args <- as.list(my_call)[-1]
    my_args$semPaths_plot <- NULL
    for (i in seq_along(my_args)) {
      my_args[[i]] <- eval(
                        my_args[[i]],
                        envir = parent.frame(),
                        enclos = parent.frame()
                      )
    }
    out <- lapply(
      semPaths_plot,
      function(x) {
        args <- my_args
        args$semPaths_plot <- x
        do.call(
          node_labels_equal_scale,
          args
        )
      }
    )

  }

  if (plot_type == "qgraph") {

  value_old <- semPaths_plot$plotOptions$label.scale.equal

  if (missing(equal_scale)) {
    equal_scale <- value_old
  }
  if (!is.logical(equal_scale)) {
    stop("equal_scale must be TRUE or FALSE")
  }
  if (length(equal_scale) > 1) {
    equal_scale <- equal_scale[1]
  }

  out <- semPaths_plot
  out$plotOptions$label.scale.equal <- equal_scale
  return(out)

  }

  # ==== Return a list of qgraphs ====

  out <- copy_class_and_attributes(
    out,
    semPaths_plot
  )

  return(out)

}

#' @rdname set_graph_attributes
#' @export
set_node_labels_equal_scale <- function(
  semPaths_plot
) {
  node_labels_equal_scale(
    semPaths_plot,
    equal_scale = TRUE
  )
}