#' @title Set the Line Types of Selected Edges
#'
#' @description Set the line types of
#' selected edges.
#'
#' @details Modified a [qgraph::qgraph]
#' object generated by
#' [semPlot::semPaths] and change the
#' widths of selected edges.
#'
#' ## Setting the value of `line_type_list`
#'
#' This argument can be set in three ways.
#'
#' For a named vector, the name of an
#' element should be the path as
#' specified by [lavaan::model.syntax]
#' or as appeared in
#' [lavaan::parameterEstimates()].
#'
#' For example, to change the line type of the
#' path regressing `y` on `x`, the name
#' should be `"y ~ x"`. To change the
#' line type of the covariance between `x1`
#' and `x2`, the name should be `"x1 ~~
#' x2"`. Therefore, `c("y ~ x1" = "dotted",
#' "x1 ~~ x2" = "dashed")` changes the
#' line types of the path from `x1` to `y`
#' and the covariance between `x1` and
#' `x2` to `"dotted"` and `"dashed"`,
#' respectively.
#'
#' The order of the two nodes *may*
#' matter for covariances. Therefore, if
#' the attribute of a covariance is not
#' changed, try switching the order of
#' the two nodes.
#'
#' For a list of named lists, each named
#' list should have three named values:
#' `from`, `to`, and `new_line_type`. The
#' attribute of the edge from `from` to
#' `to` will be set to `new_line_type`.
#'
#' The second approach is no longer
#' recommended, though kept for backward
#' compatibility.
#'
#' The third approach is one single
#' *unnamed* value. This value will be
#' applied to all edges.
#'
#' ## Supported Line Type
#'
#' The supported line types are the
#' same line types supported by
#' the `lty` argument of [par()]:
#' `"blank"` (0), `"solid"` (1),
#' `"dashed"` (2), `"dotted"` (3),
#' `"dotdash"` (4), `"longdash"` (5),
#' and `"twodash"` (6). The new line
#' type can be specified in either
#' strings or integers, but not both.
#'
#' @return A [qgraph::qgraph] based on
#' the original one, with widths for
#' selected edges changed.
#'
#'
#' @inheritParams set_edge_attribute
#'
#' @param line_type_list A named vector or a
#' list of named list. See the Details
#' section on how to set this argument.
#'
#' @examples
#' mod_pa <-
#'   'x1 ~~ x2
#'    x3 ~  x1 + x2
#'    x4 ~  x1 + x3
#'   '
#' fit_pa <- lavaan::sem(mod_pa, pa_example)
#' lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#' m <- matrix(c("x1",   NA,   NA,
#'                 NA, "x3", "x4",
#'               "x2",   NA,   NA), byrow = TRUE, 3, 3)
#' p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'             style = "ram",
#'             nCharNodes = 0, nCharEdges = 0,
#'             layout = m)
#'
#' my_line_type_vector <- c(
#'    "x2 ~~ x1" = "dotted",
#'    "x4 ~ x1" = "dashed"
#' )
#'
#' p_pa2v <- set_edge_line_type(
#'  p_pa,
#'  my_line_type_vector)
#' plot(p_pa2v)
#'
#' my_line_type_list <- list(
#'    list(
#'      from = "x1",
#'      to = "x2",
#'      new_line_type = "dotted"),
#'    list(
#'      from = "x1",
#'      to = "x4",
#'      new_line_type =  "dashed")
#'  )
#'
#' p_pa2l <- set_edge_line_type(
#'    p_pa,
#'    my_line_type_list
#'  )
#' plot(p_pa2l)
#'
#' @export

set_edge_line_type <- function(
  semPaths_plot,
  line_type_list = NULL,
  check_direction = TRUE
) {

  if (is.null(line_type_list)) {
    stop("line_type_list not specified.")
  }
  if (missing(semPaths_plot)) {
    stop("semPaths_plot not specified.")
  }

  set_all_edges <- is.null(names(line_type_list))

  # Fix the names
  line_type_list_fixed <- to_new_value(
      line_type_list,
      original_name = "new_line_type"
    )

  # Check mode

  mode_new <- sapply(
                line_type_list_fixed,
                function(x) {
                  if (is.list(x)) {
                    return(mode(x$new_value))
                  } else {
                    return(mode(x))
                  }
                }
              )

  mode_new <- unname(unique(mode_new))

  if (length(mode_new) != 1) {
    stop("Use either numbers or names of line types, but not both.")
  }

  lty_old <- get_edge_attribute(
          semPaths_plot = semPaths_plot,
          attribute_name = "lty"
        )
  mode_old <- mode(lty_old)

  if (mode_old == "numeric") {
    if (mode_new == "character") {
      if (is.list(line_type_list_fixed)) {
        for (i in seq_along(line_type_list_fixed)) {
          line_type_list_fixed[[i]]$new_value <-
            lty_character_to_integer(line_type_list_fixed[[i]]$new_value)
        }
      } else {
        line_type_list_fixed <- sapply(
            line_type_list_fixed,
            lty_character_to_integer
          )
      }
    }
  } else if (mode_old == "character") {
    if (mode_new == "numeric") {
      if (is.list(line_type_list_fixed)) {
        for (i in seq_along(line_type_list_fixed)) {
          line_type_list_fixed[[i]]$new_value <-
            lty_integer_to_character(line_type_list_fixed[[i]]$new_value)
        }
      } else {
        line_type_list_fixed <- sapply(
            line_type_list_fixed,
            lty_integer_to_character
          )
      }
    }
  } else {
    stop("Something's wrong. mode not supported in lty.")
  }

  if (set_all_edges) {
    line_type_list_fixed <- unname(line_type_list_fixed)
  }

  out <- set_edge_attribute(
          semPaths_plot = semPaths_plot,
          values = line_type_list_fixed,
          attribute_name = "lty",
          check_direction = check_direction
        )

  out
}

#' @noRd
lty_character_to_integer <- function(
  x
) {
  out <- switch(
    x,
    blank = 0L,
    solid = 1L,
    dashed = 2L,
    dotted = 3L,
    dotdash = 4L,
    longdash = 5L,
    twodash = 6L,
    NA_integer_
  )
  return(out)
}

#' @noRd
lty_integer_to_character <- function(
  x
) {
  out <- switch(
    x,
    `0` = "blank",
    `1` = "solid",
    `2` = "dashed",
    `3` = "dotted",
    `4` = "dotdash",
    `5` = "longdash",
    `6` = "twodash",
    NA_character_
  )
  return(out)
}
