#'@title Set the Curve Attributes of Selected edges
#'
#'@description Set the curve attributes of selected edges.
#'
#'@details Modified a qgraph object generated by semPaths and change the 
#'          curve attributes of selected edges.
#'
#'@return
#' A qgrpah based on the original one, with curve attributes for selected edges
#'  changed.
#' 
#'@param semPaths_plot A qgraph object generated by semPaths, or a similar qgrpah
#'                      object modified by other semptools functions.
#'@param curve_list A list of named lists. Each named list should have three 
#'                    named values: from, to, and new_curve. The curve attribute
#'                    of the edge from \code{from} to \code{to} will be set to 
#'                     \code{new_curve}.  Alternatively, it can be a named 
#'                    vector, with [`new_curve`] as the value, and the name
#'                    of each value being the name of the curve/path as in the 
#'                    [`lavaan`] model. For example, if the curve to be modified
#'                    is the path from [`x1`] to [`x4`], then the name is `x4 ~ x1`,
#'                    as appeared on the parameter table of the fit.
#'
#'@examples
#'mod_pa <- 
#'  'x1 ~~ x2
#'   x3 ~  x1 + x2
#'   x4 ~  x1 + x3
#'  '
#'fit_pa <- lavaan::sem(mod_pa, pa_example)
#'lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#'m <- matrix(c("x1",   NA,   NA,
#'                NA, "x3", "x4",
#'              "x2",   NA,   NA), byrow = TRUE, 3, 3)
#'p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'            style = "ram", 
#'            nCharNodes = 0, nCharEdges = 0,
#'            layout = m) 
#'
#'my_curve_list <- list(list(from = "x1", to = "x2", new_curve = -1),
#'                     list(from = "x1", to = "x4", new_curve =  1))
#'  
#'p_pa2 <- set_curve(p_pa, my_curve_list)
#'plot(p_pa2)
#'
#' @export

set_curve <- function(semPaths_plot, curve_list = NULL) {
    if (is.null(curve_list)) {
        stop("curve_list not specified.")
      }
    if (is.null(semPaths_plot)) {
        stop("semPaths_plot not specified.")
      } else {
        if (!inherits(semPaths_plot, "qgraph")) {
            stop("semPaths_plot is not a qgraph object.")
          }
      }

    # Convert a named vector to a named list
    if (!is.list(curve_list) && is.numeric(curve_list)) {
        curve_list_org <- curve_list
        curve_list <- to_list_of_lists(curve_list,
                                       name1 = "from",
                                       name2 = "to",
                                       name3 = "new_curve")
      }

    Nodes_names <- semPaths_plot$graphAttributes$Nodes$names
    Nodes_id <- seq_len(length(Nodes_names))
    names(Nodes_id) <- Nodes_names
    curve_old <- semPaths_plot$graphAttributes$Edges$curve
    curve_new <- curve_old
    curve_index <- sapply(curve_list, function(x) {
          edge_index(semPaths_plot, from = x$from, to = x$to)          
        })
    curve_new[curve_index] <- sapply(curve_list, function(x) x$new_curve)
    semPaths_plot$graphAttributes$Edges$curve <- curve_new
    semPaths_plot
  }
