#'@title Set the positions of edge labels of selected edges
#'
#'@description  Set the positions of edge labels of selected edges.
#'
#'@details Modified a qgraph object generated by semPaths and change the 
#'          edge label positions of selected edges.
#'
#'@return
#' A qgrpah based on the original one, with edge label positions for selected edges
#'  changed.
#' 
#'@param semPaths_plot A qgraph object generated by semPaths, or a similar qgrpah
#'                      object modified by other semptools functions.
#'@param position_list A list of named lists. Each named list should have three 
#'                    named values: from, to, and new_position. The edge label position
#'                    of the edge from \code{from} to \code{to} will be set to 
#'                     \code{new_position}. Alternatively, it can be a named 
#'                    vector, with [`new_position`] as the value, and the name
#'                    of each value being the name of the curve/path as in the 
#'                    [`lavaan`] model. For example, if the curve to be modified
#'                    is the path from [`x1`] to [`x4`], then the name is `x4 ~ x1`,
#'                    as appeared on the parameter table of the fit.
#'
#'@examples
#'mod_pa <- 
#'  'x1 ~~ x2
#'   x3 ~  x1 + x2
#'   x4 ~  x1 + x3
#'  '
#'fit_pa <- lavaan::sem(mod_pa, pa_example)
#'lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#'m <- matrix(c("x1",   NA,   NA,
#'                NA, "x3", "x4",
#'              "x2",   NA,   NA), byrow = TRUE, 3, 3)
#'p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'            style = "ram", 
#'            nCharNodes = 0, nCharEdges = 0,
#'            layout = m) 
#'
#'my_position_list <- list(list(from = "x2", to = "x3", new_position =  .25),
#'                        list(from = "x1", to = "x4", new_position =  .75))
#'  
#'  
#'p_pa2 <- set_edge_label_position(p_pa, my_position_list)
#'plot(p_pa2)
#'
#' @export

set_edge_label_position <- function(semPaths_plot, position_list = NULL) {
    if (is.null(position_list)) {
        stop("position_list not specified.")
      }
    if (is.null(semPaths_plot)) {
        stop("semPaths_plot not specified.")
      } else {
        if (!inherits(semPaths_plot, "qgraph")) {
            stop("semPaths_plot is not a qgraph object.")
          }
      }

    # Convert a named vector to a named list
    if (!is.list(position_list) && is.numeric(position_list)) {
        position_list_org <- position_list
        position_list <- to_list_of_lists(position_list,
                                       name1 = "from",
                                       name2 = "to",
                                       name3 = "new_position")
      }

    Nodes_names <- semPaths_plot$graphAttributes$Nodes$names
    Nodes_id <- seq_len(length(Nodes_names))
    names(Nodes_id) <- Nodes_names
    position_old <- semPaths_plot$graphAttributes$Edges$edge.label.position
    position_new <- position_old
    position_index <- sapply(position_list, function(x) {
          edge_index(semPaths_plot, from = x$from, to = x$to)          
        })
    position_new[position_index] <- sapply(position_list, function(x) x$new_position)
    semPaths_plot$graphAttributes$Edges$edge.label.position <- position_new
    semPaths_plot
  }
