#' @title Set Edge Label Attributes of
#' Selected Edges
#'
#' @description Set the attributes of
#' selected edges, such as the label
#' position.
#'
#' @details Modify a [qgraph::qgraph]
#' object generated by
#' [semPlot::semPaths] and change the
#' attributes of the edge label of
#' selected edges.
#'
#' Currently, the following attributes
#' are supported:
#'
#' - Edge label position.
#'
#' - Edge label content.
#'
#' - Edge label background color.
#'
#' - Edge label size.
#'
#' ## How to specify the values
#'
#' There are three approach to
#' specify the value.
#'
#' First, the values can be a named
#' vector of the values, the recommended
#' approach. The name of an
#' element should be the path as
#' specified by [lavaan::model.syntax]
#' or as appeared in
#' [lavaan::parameterEstimates()]. For
#' example, to change position of the
#' edge label of the path regressing `y`
#' on `x`, the name should be `"y ~ x"`.
#'
#' Second, the values can be specified
#' by a list of named lists, each named
#' list should have three named values:
#' `from`, `to`, and the new value (name
#' depends on the attribute). The value
#' of the edge label of the edge from
#' `from` to `to` will be set to this
#' new value. For example, for
#' [set_edge_label_position()],
#' `list(list(from = "x1", to = "y",
#' new_position = .2), list(from = "x2",
#' to = "y", new_position = .7))` is
#' equivalent to the named vector above.
#'
#' The second approach is no longer
#' recommended. It was supported for
#' backward compatibility.
#'
#' Third, the value can be a single
#' value, which will be used to set the
#' attribute of all edges.
#'
#' ## Setting Edge Position
#'
#' When setting the edge position,
#' the value is the position. The
#' mid-point of the edge is 0.5. The
#' closer the value to 1, the closer the
#' label to the left-hand-side node (`y`
#' in this example). The closer the
#' value to 0, the close the label to
#' the right-hand-side node (`x` in this
#' example). For example, `c("y ~ x1" =
#' .2, "y ~ x2" = .7)` moves the path
#' coefficient from `x1` to `y` closer
#' to `x`, and the path coefficient from
#' `x2` to `y` closer to `y`.
#'
#' ## Setting Label Size
#'
#' The function [set_edge_label_size()]
#' works in two modes. With `how = "ratio"`,
#' the new label size is the original
#' size multiplied by the supplied value.
#' For example, if the value is 2, the size
#' of a label is doubled. With `how = "value"`,
#' the new size is set to be equal to the
#' supplied value. For example, if the value is
#' 2, the size of a label is set to 2.
#'
#  @return A [qgraph::qgraph] based on
#  the original one, with edge
#' label positions for selected edges
#' changed.
#' If `semPaths_plot` is a list of
#' [qgraph::qgraph] objects, then a
#' list of processed [qgraph::qgraph] objects
#' will be returned.
#'
#' @inheritParams set_edge_attribute
#'
#' @name set_edge_label_attributes
NULL

#' @param position_list The new
#' position. See 'Details' on how to set
#' this argument. If a list of named
#' list is used, the element for new
#' position should be named
#' `new_position`.
#'
#' @examples
#' mod_pa <-
#'   'x1 ~~ x2
#'    x3 ~  x1 + x2
#'    x4 ~  x1 + x3
#'   '
#' fit_pa <- lavaan::sem(mod_pa, pa_example)
#' lavaan::parameterEstimates(fit_pa)[, c("lhs", "op", "rhs", "est", "pvalue")]
#' m <- matrix(c("x1",   NA,   NA,
#'                 NA, "x3", "x4",
#'               "x2",   NA,   NA), byrow = TRUE, 3, 3)
#' p_pa <- semPlot::semPaths(fit_pa, whatLabels="est",
#'             style = "ram",
#'             nCharNodes = 0, nCharEdges = 0,
#'             layout = m)
#'
#' # ==== set_edge_label_position ====
#'
#' my_position_vector <- c(
#'   "x3 ~ x2" = .25,
#'   "x4 ~ x1" = .75
#' )
#' p_pa2v <- set_edge_label_position(
#'              p_pa,
#'              my_position_vector
#'            )
#' plot(p_pa2v)
#'
#' # This approach is no longer recommended
#' my_position_list <- list(
#'                      list(
#'                        from = "x2",
#'                        to = "x3",
#'                        new_position = .25
#'                       ),
#'                      list(
#'                        from = "x1",
#'                        to = "x4",
#'                        new_position = .75)
#'                      )
#' p_pa2l <- set_edge_label_position(
#'              p_pa,
#'              my_position_list
#'            )
#' plot(p_pa2l)
#'
#' @rdname set_edge_label_attributes
#' @export
set_edge_label_position <- function(
  semPaths_plot,
  position_list = NULL,
  check_direction = TRUE
) {
  # An option to use 0.3.3 version, just in case
  mimic_033 <- getOption("semptools.mimic_033", FALSE)
  if (isTRUE(mimic_033)) {
    return(set_edge_label_position_old(
      semPaths_plot = semPaths_plot,
      position_list = position_list
    ))
  }
  # This version use set_edge_attribute()

  if (is.null(position_list)) {
    stop("position_list not specified.")
  }
  if (is.null(semPaths_plot)) {
    stop("semPaths_plot not specified.")
  }

  # Fix the names
  position_list_fixed <- to_new_value(
    position_list,
    original_name = "new_position"
  )
  out <- set_edge_attribute(semPaths_plot = semPaths_plot,
                            values = position_list_fixed,
                            attribute_name = "edge.label.position",
                            check_direction = check_direction)

  out
}

#' @param label_list The new label. See
#' 'Details' on how to set this
#' argument. If a list of named list is
#' used, the element for new label
#' should be named `new_label`.
#'
#' @examples
#'
#' # ==== set_edge_label ====
#'
#' my_label_vector <- c(
#'   "x3 ~ x2" = "a",
#'   "x4 ~ x1" = "b"
#' )
#' p_pa3v <- set_edge_label(
#'              p_pa,
#'              my_label_vector
#'            )
#' plot(p_pa3v)
#'
#' # This approach is no longer recommended
#' my_label_list <- list(
#'                      list(
#'                        from = "x2",
#'                        to = "x3",
#'                        new_label = "a"
#'                       ),
#'                      list(
#'                        from = "x1",
#'                        to = "x4",
#'                        new_position = "a")
#'                      )
#' p_pa3l <- set_edge_label(
#'              p_pa,
#'              my_label_list
#'            )
#' plot(p_pa3l)
#'
#' @rdname set_edge_label_attributes
#' @export
set_edge_label <- function(
  semPaths_plot,
  label_list = NULL,
  check_direction = TRUE
) {

  # This version use set_edge_attribute()

  if (is.null(label_list)) {
    stop("label_list not specified.")
  }
  if (is.null(semPaths_plot)) {
    stop("semPaths_plot not specified.")
  }

  # Fix the names
  label_list_fixed <- to_new_value(
    label_list,
    original_name = "new_label"
  )
  out <- set_edge_attribute(semPaths_plot = semPaths_plot,
                            values = label_list_fixed,
                            attribute_name = "labels",
                            check_direction = check_direction)

  out
}

#' @param label_bg_list The new
#' background color. See 'Details' on
#' how to set this argument. If a list
#' of named list is used, the element
#' for new background color should be
#' named `new_label_bg`.
#'
#' @examples
#'
#' # ==== set_edge_label_bg ====
#'
#' my_label_bg_vector <- c(
#'   "x3 ~ x2" = "red",
#'   "x4 ~ x1" = "#00FF00"
#' )
#' p_pa4v <- set_edge_label_bg(
#'              p_pa,
#'              my_label_bg_vector
#'            )
#' plot(p_pa4v)
#'
#' # This approach is no longer recommended
#' my_label_bg_list <- list(
#'                      list(
#'                        from = "x2",
#'                        to = "x3",
#'                        new_label_bg = "red"
#'                       ),
#'                      list(
#'                        from = "x1",
#'                        to = "x4",
#'                        new_label_bg = "#00FF00")
#'                      )
#' p_pa4l <- set_edge_label_bg(
#'              p_pa,
#'              my_label_bg_list
#'            )
#' plot(p_pa4l)
#'
#'
#' @rdname set_edge_label_attributes
#' @export
set_edge_label_bg <- function(
  semPaths_plot,
  label_bg_list = NULL,
  check_direction = TRUE
) {

  # This version use set_edge_attribute()

  if (is.null(label_bg_list)) {
    stop("label_bg_list not specified.")
  }
  if (is.null(semPaths_plot)) {
    stop("semPaths_plot not specified.")
  }

  # Fix the names
  label_bg_list_fixed <- to_new_value(
    label_bg_list,
    original_name = "new_label_bg"
  )
  out <- set_edge_attribute(semPaths_plot = semPaths_plot,
                            values = label_bg_list_fixed,
                            attribute_name = "label.bg",
                            check_direction = check_direction)

  out
}


#' @param label_size_list How the
#' label sizes are to be changed.
#' See 'Details' on
#' how to set this argument. If a list
#' of named list is used, the element
#' for new background color should be
#' named `new_label_size`.
#'
#' @examples
#'
#' # ==== set_edge_label_size ====
#'
#' my_label_size_vector <- c(
#'   "x3 ~ x2" = 2,
#'   "x4 ~ x1" = 3
#' )
#' p_pa5v <- set_edge_label_size(
#'              p_pa,
#'              my_label_size_vector
#'            )
#' plot(p_pa5v)
#'
#' # This approach is no longer recommended
#' my_label_size_list <- list(
#'                      list(
#'                        from = "x2",
#'                        to = "x3",
#'                        new_label_size = 2
#'                       ),
#'                      list(
#'                        from = "x1",
#'                        to = "x4",
#'                        new_label_size = 3)
#'                      )
#' p_pa5l <- set_edge_label_size(
#'              p_pa,
#'              my_label_size_list
#'            )
#' plot(p_pa5l)
#'
#'
#' @rdname set_edge_label_attributes
#' @export
set_edge_label_size <- function(
  semPaths_plot,
  label_size_list = NULL,
  how = c("ratio", "value"),
  check_direction = TRUE
) {

  how <- match.arg(how)

  # This version use set_edge_attribute()

  if (is.null(label_size_list)) {
    stop("label_size_list not specified.")
  }
  if (is.null(semPaths_plot)) {
    stop("semPaths_plot not specified.")
  }

  # Fix the names
  label_size_list_fixed <- to_new_value(
    label_size_list,
    original_name = "new_label_size"
  )
  out <- set_edge_attribute(semPaths_plot = semPaths_plot,
                            values = label_size_list_fixed,
                            attribute_name = "label.cex",
                            how = how,
                            check_direction = check_direction)

  out
}

#' @noRd
set_edge_label_position_old <- function(semPaths_plot, position_list = NULL) {
    # TODO:
    # - Update to use set_edge_attribute().
    if (is.null(position_list)) {
        stop("position_list not specified.")
      }
    if (is.null(semPaths_plot)) {
        stop("semPaths_plot not specified.")
      } else {
        if (!inherits(semPaths_plot, "qgraph")) {
            stop("semPaths_plot is not a qgraph object.")
          }
      }

    # Convert a named vector to a named list
    if (!is.list(position_list) && is.numeric(position_list)) {
        position_list_org <- position_list
        position_list <- to_list_of_lists(position_list,
                                       name1 = "from",
                                       name2 = "to",
                                       name3 = "new_position")
      }

    Nodes_names <- semPaths_plot$graphAttributes$Nodes$names
    Nodes_id <- seq_len(length(Nodes_names))
    names(Nodes_id) <- Nodes_names
    position_old <- semPaths_plot$graphAttributes$Edges$edge.label.position
    position_new <- position_old
    position_index <- sapply(position_list, function(x) {
          edge_index(semPaths_plot, from = x$from, to = x$to)
        })
    position_new[position_index] <- sapply(position_list, function(x) x$new_position)

    # Check bidirectional edges
    position_list2 <- position_list[which(semPaths_plot$Edge$bidirectional[position_index])]
    if (length(position_list2) > 0) {
      position_index2 <- sapply(position_list2, function(x) {
            edge_index(semPaths_plot, from = x$to, to = x$from)
         })
      position_new[position_index2] <- sapply(position_list2, function(x) x$new_position)
    }

    semPaths_plot$graphAttributes$Edges$edge.label.position <- position_new
    semPaths_plot
  }
